### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by LinYunWen** [anenasa/androidtv-news#1]
這幾天 youtube 來源的新聞都會無法讀取並出現此錯誤
看起來是因為 yt-dlp 那邊的問題

可能要追蹤一下他們包出新版的時候，更新 lib
- [Issue #6253 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/6253)、[Issue #6247 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/6247)
- [Issue #216 · yausername/youtubedl-android](https://github.com/yausername/youtubedl-android/issues/216)

非常感謝，這個 app 真的很讚

**Comment by anenasa** [comment]
請下載2.0.1版，然後進入「設定」，按下「更新」，這樣應該就能看了 
https://github.com/anenasa/androidtv-news/commit/7ffce649033c376b1a8892a2fdbfd9866bacdedb
