### ISSUE TITLE
提個建議～可否一開啟APP時 就清除所有影片快取～這様或許會更好用～感恩作者～

### ISSUE THREAD

**Issue by charles0568** [anenasa/androidtv-news#2]
提個建議～可否一開啟APP時 就清除所有影片快取～這様或許會更好用～感恩作者～

**Comment by anenasa** [comment]
好，我看看怎麼改

**Comment by anenasa** [comment]
Fix in https://github.com/anenasa/androidtv-news/commit/2ed19c71d878d45795ddf9845df45ecd5d22f377
