### ISSUE TITLE
GoogleTV更新到新版本之後，會發生閃退情形

### ISSUE THREAD

**Issue by impj-tw** [anenasa/androidtv-news#3]
1.GoogleTV更新到新版本之後，會發生閃退情形，即點選程式後，出現短暫黑畫面，即又回到主畫面，如果沒有執行系統更新，則3.3包含前一版都可以正常執行，附加檔案為GoogleTV更新版本號
![temp1](https://github.com/user-attachments/assets/8a856207-2508-40e0-a72c-03bc706558bc)

2.另想請問，關於3.3版不顯示錯誤訊息，請問是否有機會做成選項打開，因為追部分YouTube或Friday新聞台，如果因頻道異動出現錯誤訊息，會比較方便判斷，例如有些直播尚未開始可以看到yt-dlp回應還有幾分鐘後開始，或者出錯了可以明確知道發生什麼事去修改自己的config.txt

以上問題再麻煩您了

**Comment by anenasa** [comment]
1. 試試3.4.0還會不會閃退，如果還會就把 Android/data/io.github.anenasa.news/files/log.txt 傳給我，我看看是什麼問題
2. 之後會加選項

**Comment by impj-tw** [comment]
您好，3.4.0安裝後可正常運作

**Comment by anenasa** [comment]
3.5.0已加入顯示錯誤訊息選項
